// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  feature: dynamic(() => import("./Feature")),
  hero: dynamic(() => import("./Hero")),
};
